/// Exercise IDs with a real male/female demonstration photo pair
/// sourced from Pexels (see gendered_exercise_images_mapping.json) —
/// for exercises free-exercise-db had no safe match for. Bundled as
/// `assets/data/exercise_images/<id>-male.jpg` and `-female.jpg`.
///
/// Regenerated by tool/import_gendered_exercise_images.py — do not hand-edit.
const Set<String> kGenderedExercisePhotos = {
  'bulgarian-split-squat',
  'burpee',
  'calf-raise',
  'cat-cow',
  'chest-supported-row',
  'diamond-push-up',
  'glute-bridge',
  'high-knees',
  'jumping-jacks',
  'kettlebell-swing',
  'lunge',
  'side-plank',
  'single-arm-cable-row',
};
